apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  #This defines which pods are going be represented by this service 
  # the service becomes a network endpoint for either other service
  # or maybe external users to connect to 

  selector:
    app: webapp
    release: "0"

  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort